### ISSUE TITLE
Can not find setup_ld_path.sh 

### ISSUE THREAD

**Issue by Stephenhua** [uibk-iNNference/eNNclave#1]
I clone this project to my local. I can not find the setup_ld_path.sh according the ReadMe.md. Therefore, How can I build the project. Could you give more details about how to build  this project. Thanks.

**Comment by alxshine** [comment]
Hi, thanks for raising this issue.
It seems the script got lost when moving repositories. I'm on mobile, but I'll add it when i have the time.

The lines you want are
```
export LD_LIBRARY_PATH="${ENNCLAVE_HOME}/lib:$LD_LIBRARY_PATH"
export PYTHONPATH="${ENNCLAVE_HOME}/lib:$PYTHONPATH"
```

Where `ENNCLAVE_HOME` is the path to your cloned repo.

Hope this helps :)

**Comment by Stephenhua** [comment]
Ok，I know what's your means. I have anther questions. I get pull this repo, but I do not know how to build this project. Could you give me more details steps about how to build eNNclaves and how to use it. Thanks.

**Comment by alxshine** [comment]
It's probably best if you look at our [experiments repository](https://github.com/uibk-iNNference/eNNclave-experiments). There you can download the pretrained models and the heading "performance evaluation" will tell you how to compile and use the code :)
